server:
  port: 8080
spring:
  application:
    name: TrustMeBank
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

jwt:
  encodedSigningKey: H8aUSA5regz2w2sniXu8Io8cdzYsorque/XlnaLvTYvYKcKEClFTqBRc84an5bQxLWMc5TyMkqfuS9AZxcF+hw== #base64

logging:
  level:
    org.springframework.security: INFO